version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_WS_URL=http://localhost:3001
      - NEXT_PUBLIC_SYNC_URL=http://localhost:3001
      - NEXT_PUBLIC_COLLAB_WS_URL=ws://localhost:3002
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    ports:
      - "3001:3001"
      - "3002:3002"
    environment:
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - NODE_ENV=production
    volumes:
      - ./data:/app/data

volumes:
  data: