version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vibe-kanban
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - FRONTEND_URL=http://localhost:3000
      - NEXT_PUBLIC_WS_URL=http://localhost:3001
      - NEXT_PUBLIC_SYNC_URL=http://localhost:3001
      - NEXT_PUBLIC_COLLAB_WS_URL=ws://localhost:3002
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  data:
    driver: local

networks:
  default:
    name: vibe-kanban-network